task:
  name: "Firmware Dump by DumprX"
  only_if: $CIRRUS_REPO_OWNER == 'DumprX'
  skip: $CIRRUS_BRANCH == 'main'
  auto_cancellation: $CIRRUS_BRANCH == 'autocancel'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      privileged: true
      cpu: 4
      memory: 16G
